name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn install
      working-directory: frontend/my-app  # Set working directory
    - name: Build
      run: yarn build
      working-directory: frontend/my-app  # Set working directory
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
        channelId: live
        projectId: milestone1-416419
